-- ============================================================================
-- Script 01: Crear tablas DISTRIBUIDAS en COMEE - COLUMNAS CORRECTAS
-- Ejecutar en: COMEE como u_comee
-- Estas tablas SOLO existen en COMEE (no están en PROD, se acceden vía sinónimos)
-- ============================================================================

SET SERVEROUTPUT ON;
PROMPT ════════════════════════════════════════════════════════════════
PROMPT Creando tablas DISTRIBUIDAS en COMEE
PROMPT (Según migraciones de Laravel)
PROMPT ════════════════════════════════════════════════════════════════

-- DATOS_FACTURACION - Debe crearse primero (PEDIDOS depende de ella)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DATOS_FACTURACION CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE DATOS_FACTURACION (
    DAF_Codigo VARCHAR2(15) PRIMARY KEY,
    DAF_CLI_Codigo VARCHAR2(13) NOT NULL,
    DAF_Direccion VARCHAR2(255),
    DAF_Ciudad VARCHAR2(255),
    DAF_Estado VARCHAR2(255),
    DAF_CP VARCHAR2(10),
    DAF_Tarjeta_Numero CLOB,
    DAF_Tarjeta_Expiracion VARCHAR2(5),
    DAF_Tarjeta_CVV CLOB,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT fk_datos_fac_cliente FOREIGN KEY (DAF_CLI_Codigo) 
        REFERENCES CLIENTES(CLI_Ced_Ruc) ON DELETE CASCADE
);

PROMPT ✓ Tabla DATOS_FACTURACION creada

-- CARRITOS (solo COMEE)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CARRITOS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE CARRITOS (
    CRC_Carrito VARCHAR2(13) PRIMARY KEY,
    CLI_Ced_Ruc VARCHAR2(13),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT fk_carritos_cliente FOREIGN KEY (CLI_Ced_Ruc) 
        REFERENCES CLIENTES(CLI_Ced_Ruc) ON DELETE CASCADE
);

PROMPT ✓ Tabla CARRITOS creada

-- DETALLE_CARRITO (solo COMEE)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DETALLE_CARRITO CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE DETALLE_CARRITO (
    CRC_Carrito VARCHAR2(13) NOT NULL,
    PRO_Codigo VARCHAR2(20) NOT NULL,
    CRD_Cantidad NUMBER NOT NULL,
    CRD_Talla VARCHAR2(50),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT fk_detalle_carrito FOREIGN KEY (CRC_Carrito) 
        REFERENCES CARRITOS(CRC_Carrito) ON DELETE CASCADE,
    CONSTRAINT fk_detalle_car_producto FOREIGN KEY (PRO_Codigo) 
        REFERENCES PRODUCTOS(PRO_Codigo) ON DELETE CASCADE
);

PROMPT ✓ Tabla DETALLE_CARRITO creada

-- DETALLE_FACTURA (solo COMEE)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DETALLE_FACTURA CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE DETALLE_FACTURA (
    FAC_Codigo VARCHAR2(15) NOT NULL,
    PRO_Codigo VARCHAR2(20) NOT NULL,
    DFC_Cantidad NUMBER NOT NULL,
    DFC_Precio NUMBER(10,2) NOT NULL,
    DFC_Talla VARCHAR2(50),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT fk_detalle_factura FOREIGN KEY (FAC_Codigo) 
        REFERENCES FACTURAS(FAC_Codigo) ON DELETE CASCADE,
    CONSTRAINT fk_detalle_fac_producto FOREIGN KEY (PRO_Codigo) 
        REFERENCES PRODUCTOS(PRO_Codigo) ON DELETE CASCADE
);

PROMPT ✓ Tabla DETALLE_FACTURA creada

-- PEDIDOS (solo COMEE) - Debe crearse después de DATOS_FACTURACION y FACTURAS
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE PEDIDOS (
    PED_Codigo VARCHAR2(15) PRIMARY KEY,
    PED_CLI_Codigo VARCHAR2(13) NOT NULL,
    PED_DAF_Codigo VARCHAR2(15) NOT NULL,
    PED_FAC_Codigo VARCHAR2(15),
    PED_Fecha TIMESTAMP NOT NULL,
    PED_Estado VARCHAR2(20) DEFAULT 'Pendiente' CHECK (PED_Estado IN ('Pendiente', 'Procesando', 'Enviado', 'Entregado')),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT fk_pedidos_cliente FOREIGN KEY (PED_CLI_Codigo) 
        REFERENCES CLIENTES(CLI_Ced_Ruc) ON DELETE CASCADE,
    CONSTRAINT fk_pedidos_datos_fac FOREIGN KEY (PED_DAF_Codigo) 
        REFERENCES DATOS_FACTURACION(DAF_Codigo) ON DELETE CASCADE,
    CONSTRAINT fk_pedidos_factura FOREIGN KEY (PED_FAC_Codigo) 
        REFERENCES FACTURAS(FAC_Codigo) ON DELETE CASCADE
);

PROMPT ✓ Tabla PEDIDOS creada

PROMPT
PROMPT ════════════════════════════════════════════════════════════════
PROMPT Tablas DISTRIBUIDAS creadas exitosamente en COMEE
PROMPT ════════════════════════════════════════════════════════════════
PROMPT
PROMPT Tablas creadas:
PROMPT   - DATOS_FACTURACION
PROMPT   - CARRITOS
PROMPT   - DETALLE_CARRITO
PROMPT   - DETALLE_FACTURA
PROMPT   - PEDIDOS
PROMPT

EXIT;
