-- ============================================================================
-- SCRIPT: create_db_users.sql
-- Descripción: Crea usuarios de Base de Datos Oracle y les asigna los roles del proyecto.
-- Ejecutar como SYSTEM o ADMIN.
-- ============================================================================

SET SERVEROUTPUT ON;

BEGIN
    -- 1. Usuario U_ADMIN_PROD (Administrador DB)
    BEGIN
        EXECUTE IMMEDIATE 'CREATE USER U_ADMIN_PROD IDENTIFIED BY "Admin123!"';
        EXECUTE IMMEDIATE 'ALTER USER U_ADMIN_PROD ACCOUNT UNLOCK';
        EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CONNECT, RESOURCE TO U_ADMIN_PROD';
        EXECUTE IMMEDIATE 'GRANT ROLE_ADMIN_PROD TO U_ADMIN_PROD';
        DBMS_OUTPUT.PUT_LINE('Usuario U_ADMIN_PROD creado/actualizado.');
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE = -1920 THEN
                EXECUTE IMMEDIATE 'ALTER USER U_ADMIN_PROD IDENTIFIED BY "Admin123!"';
                EXECUTE IMMEDIATE 'ALTER USER U_ADMIN_PROD ACCOUNT UNLOCK';
                EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CONNECT, RESOURCE TO U_ADMIN_PROD';
                EXECUTE IMMEDIATE 'GRANT ROLE_ADMIN_PROD TO U_ADMIN_PROD';
                DBMS_OUTPUT.PUT_LINE('U_ADMIN_PROD ya existía, permisos reafirmados.');
            ELSE RAISE; END IF;
    END;

    -- 2. Usuario U_GESTOR_INV (Gestor de Inventario)
    BEGIN
        EXECUTE IMMEDIATE 'CREATE USER U_GESTOR_INV IDENTIFIED BY "Gestor123!"';
        EXECUTE IMMEDIATE 'ALTER USER U_GESTOR_INV ACCOUNT UNLOCK';
        EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CONNECT TO U_GESTOR_INV';
        EXECUTE IMMEDIATE 'GRANT ROLE_GESTOR_INV TO U_GESTOR_INV';
        DBMS_OUTPUT.PUT_LINE('Usuario U_GESTOR_INV creado/actualizado.');
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE = -1920 THEN
                EXECUTE IMMEDIATE 'ALTER USER U_GESTOR_INV IDENTIFIED BY "Gestor123!"';
                EXECUTE IMMEDIATE 'ALTER USER U_GESTOR_INV ACCOUNT UNLOCK';
                EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CONNECT TO U_GESTOR_INV';
                EXECUTE IMMEDIATE 'GRANT ROLE_GESTOR_INV TO U_GESTOR_INV';
                DBMS_OUTPUT.PUT_LINE('U_GESTOR_INV ya existía, permisos reafirmados.');
            ELSE RAISE; END IF;
    END;
    
    -- 3. Usuario U_APP_FRONTEND (Cliente Frontend)
    BEGIN
        EXECUTE IMMEDIATE 'CREATE USER U_APP_FRONTEND IDENTIFIED BY "Front123!"';
        EXECUTE IMMEDIATE 'ALTER USER U_APP_FRONTEND ACCOUNT UNLOCK';
        EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CONNECT TO U_APP_FRONTEND';
        EXECUTE IMMEDIATE 'GRANT ROLE_APP_FRONTEND TO U_APP_FRONTEND';
        DBMS_OUTPUT.PUT_LINE('Usuario U_APP_FRONTEND creado/actualizado.');
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE = -1920 THEN
                EXECUTE IMMEDIATE 'ALTER USER U_APP_FRONTEND IDENTIFIED BY "Front123!"';
                EXECUTE IMMEDIATE 'ALTER USER U_APP_FRONTEND ACCOUNT UNLOCK';
                EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CONNECT TO U_APP_FRONTEND';
                EXECUTE IMMEDIATE 'GRANT ROLE_APP_FRONTEND TO U_APP_FRONTEND';
                DBMS_OUTPUT.PUT_LINE('U_APP_FRONTEND ya existía, permisos reafirmados.');
            ELSE RAISE; END IF;
    END;
END;
/
