<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use App\Models\{Pedido, Carrito, DatosFacturacion};
use LaravelDaily\Invoices\Invoice;
use LaravelDaily\Invoices\Classes\{Buyer, Party, InvoiceItem};

class CheckoutController extends Controller
{
    public function index()
    {
        // Ensure user is logged in (handled by middleware usually, but check here too)
        if (!Auth::guard('client')->check()) {
            return redirect()->route('client.login');
        }

        $user = Auth::guard('client')->user();
        $cliente = $user->cliente; // Access the Cliente model related to User

        // Fetch saved billing data
        $savedProfiles = DatosFacturacion::where('DAF_CLI_Codigo', $cliente->CLI_Ced_Ruc)->get();

        return view('client.checkout.index', compact('cliente', 'savedProfiles'));
    }

    public function processPayment(Request $request)
    {
        $request->validate([
            'direccion' => 'required|string|max:255',
            'ciudad' => 'required|string|max:100',
            'estado' => 'required|string|max:100',
            'cp' => 'required|string|max:10',
            'card_number' => 'required|string|min:15|max:19', // Basic length check
            'card_expiry' => 'required|string|size:5', // MM/YY
            'card_cvv' => 'required|string|min:3|max:4',
            'cart_items' => 'required|json', // Cart items passed as JSON string
        ]);

        $user = Auth::guard('client')->user();
        $cliente = $user->cliente;

        try {
            DB::beginTransaction();

            // 1. Create/Update DatosFacturacion
            $datosFacturacion = DatosFacturacion::create([
                'DAF_CLI_Codigo' => $cliente->CLI_Ced_Ruc,
                'DAF_Direccion' => $request->direccion,
                'DAF_Ciudad' => $request->ciudad,
                'DAF_Estado' => $request->estado,
                'DAF_CP' => $request->cp,
                'DAF_Tarjeta_Numero' => $request->card_number, // Cast encrypted
                'DAF_Tarjeta_Expiracion' => $request->card_expiry,
                'DAF_Tarjeta_CVV' => $request->card_cvv, // Cast encrypted
            ]);

            // 2. Create Factura
            // Calculate totals again for security
            $cartItems = json_decode($request->cart_items, true);
            $subtotal = 0;
            foreach ($cartItems as $item) {
                // Determine quantity key (qty or quantity)
                $qty = $item['qty'] ?? $item['quantity'] ?? 1;
                $subtotal += $item['price'] * $qty;
            }
            $ivaRate = config('urbanhoops.iva', 15) / 100;
            $iva = $subtotal * $ivaRate;
            $total = $subtotal + $iva;

            $facturaId = \App\Models\Factura::generateId();

            $factura = \App\Models\Factura::create([
                'FAC_Codigo' => $facturaId,
                'CLI_Ced_Ruc' => $cliente->CLI_Ced_Ruc,
                'FAC_Subtotal' => $subtotal,
                'FAC_IVA' => $iva,
                'FAC_Total' => $total,
                'FAC_Estado' => 'Pag', // Automatically paid since it's a card checkout
            ]);

            // 3. Create DetalleFactura items
            // 3. Create DetalleFactura items
            foreach ($cartItems as $item) {
                $qty = $item['qty'] ?? $item['quantity'] ?? 1;
                $talla = $item['talla'] ?? $item['size'] ?? null;

                DB::table('detalle_factura')->insert([
                    'FAC_Codigo' => $factura->FAC_Codigo,
                    'PRO_Codigo' => $item['id'], // Assuming id matches PRO_Codigo
                    'DFC_Cantidad' => $qty,
                    'DFC_Precio' => $item['price'],
                    'DFC_Talla' => $talla,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }

            // Clear Server-Side Cart
            // DB::table('carritos')->where('CLI_Ced_Ruc', $cliente->CLI_Ced_Ruc)->delete(); OR via Model
            Carrito::where('CLI_Ced_Ruc', $cliente->CLI_Ced_Ruc)->delete();

            // 4. Create Pedido (Linked to Factura)
            $pedido = Pedido::create([
                'PED_CLI_Codigo' => $cliente->CLI_Ced_Ruc,
                'PED_DAF_Codigo' => $datosFacturacion->DAF_Codigo,
                'PED_FAC_Codigo' => $factura->FAC_Codigo,
                'PED_Fecha' => now(),
                'PED_Codigo' => null, // Let boot handle it
                'PED_Estado' => 'Procesando'
            ]);

            // 5. Update Inventory (Kardex)
            $bodega = \App\Models\Bodega::first();
            if (!$bodega) {
                // Create default bodega if missing to ensure transaction works
                $bodega = \App\Models\Bodega::create([
                    'BOD_Nombre' => 'Bodega Central', // ID auto-generated by boot
                    'BOD_Direccion' => 'Principal',
                    'BOD_Ciudad' => 'Quito',
                    'BOD_Pais' => 'Ecuador',
                    'BOD_CodigoPostal' => '170505',
                    'BOD_Responsable' => 'Sistema'
                ]);
            }

            \App\Models\Kardex::crearMovimiento([
                'TRN_Codigo' => 'T04', // Venta de Productos
                'FAC_Codigo' => $factura->FAC_Codigo,
                'BOD_Codigo' => $bodega->BOD_Codigo
            ]);

            DB::commit();

            return response()->json([
                'success' => true,
                'redirect_url' => route('client.checkout.success', ['order' => $pedido->PED_Codigo])
            ]);
        } catch (\Exception $e) {
            DB::rollBack();
            return response()->json(['success' => false, 'message' => 'Error al procesar el pedido: ' . $e->getMessage()], 500);
        }
    }

    public function success($orderId)
    {
        $pedido = Pedido::with('factura.productos', 'datosFacturacion')->findOrFail($orderId);

        // Security check: ensure order belongs to current user
        $user = Auth::guard('client')->user();

        // Debug logging
        \Illuminate\Support\Facades\Log::info('Checkout Success Debug:', [
            'pedido_cli_codigo' => $pedido->PED_CLI_Codigo,
            'user_cli_ced_ruc' => $user->cliente->CLI_Ced_Ruc,
            'match' => $pedido->PED_CLI_Codigo === $user->cliente->CLI_Ced_Ruc
        ]);

        $orderCli = trim((string)$pedido->PED_CLI_Codigo);
        $userCli = trim((string)$user->cliente->CLI_Ced_Ruc);

        if ($orderCli !== $userCli) {
            abort(403, "Unauthorized: Mismatch Order('{$orderCli}') vs User('{$userCli}')");
        }

        // Load products with fallback for Oracle
        $productos = $pedido->factura->productos;

        if ($productos->isEmpty()) {
            $detalles = DB::table('detalle_factura')
                ->where(DB::raw('UPPER(FAC_CODIGO)'), strtoupper($pedido->factura->FAC_Codigo))
                ->get();

            $tempProductos = collect();
            foreach ($detalles as $detalle) {
                $proCodigo = $detalle->PRO_CODIGO ?? $detalle->pro_codigo ?? $detalle->PRO_Codigo;
                $productoData = DB::table('productos')
                    ->where(DB::raw('UPPER(PRO_CODIGO)'), strtoupper($proCodigo))
                    ->first();

                if ($productoData) {
                    // Manually hydrate simple object or model
                    $prod = new \App\Models\Producto((array)$productoData);
                    // Fix attributes casing if needed, but constructor handles it if keys match fillable
                    // Force set attributes that might be missing due to strict fillable validation in hydration
                    $prod->PRO_Nombre = $productoData->PRO_NOMBRE ?? $productoData->pro_nombre ?? $productoData->PRO_Nombre;
                    $prod->PRO_Imagen = $productoData->PRO_IMAGEN ?? $productoData->pro_imagen ?? $productoData->PRO_Imagen;

                    // Mock Pivot
                    $pivot = new \stdClass();
                    $pivot->DFC_CANTIDAD = $detalle->DFC_CANTIDAD ?? $detalle->dfc_cantidad ?? $detalle->DFC_Cantidad;
                    $pivot->DFC_PRECIO = $detalle->DFC_PRECIO ?? $detalle->dfc_precio ?? $detalle->DFC_Precio;
                    $pivot->DFC_TALLA = $detalle->DFC_TALLA ?? $detalle->dfc_talla ?? $detalle->DFC_Talla;

                    $prod->setRelation('pivot', $pivot);
                    $tempProductos->push($prod);
                }
            }
            $productos = $tempProductos;
        }

        return view('client.checkout.success', compact('pedido', 'productos'));
    }

    /**
     * Generate and download invoice PDF
     */
    public function downloadInvoice($orderId)
    {
        $pedido = Pedido::with('factura.productos', 'datosFacturacion', 'cliente')->findOrFail($orderId);

        // Security check
        $user = Auth::guard('client')->user();
        $orderCli = trim((string)$pedido->PED_CLI_Codigo);
        $userCli = trim((string)$user->cliente->CLI_Ced_Ruc);

        if ($orderCli !== $userCli) {
            abort(403, "Unauthorized: Mismatch Order('{$orderCli}') vs User('{$userCli}')");
        }

        if (!$pedido->factura) {
            abort(404, 'Factura no encontrada');
        }

        return $this->generateInvoicePDF($pedido);
    }

    /**
     * Generate invoice PDF
     */
    private function generateInvoicePDF($pedido)
    {
        $factura = $pedido->factura;
        $cliente = $pedido->cliente;

        // Create buyer
        $buyer = new Buyer([
            'name' => $cliente->CLI_Nombre,
            'custom_fields' => [
                'Cédula/RUC' => $cliente->CLI_Ced_Ruc,
                'Teléfono' => $cliente->CLI_Telefono,
                'Email' => $cliente->CLI_Correo,
            ],
        ]);

        // Create invoice items
        // Create invoice items
        $items = [];
        $productos = $factura->productos;

        if ($productos->isEmpty()) {
            // Fallback: Manual query to handle Oracle case sensitivity issues
            $detalles = DB::table('detalle_factura')
                ->where(DB::raw('UPPER(FAC_CODIGO)'), strtoupper($factura->FAC_Codigo))
                ->get();

            foreach ($detalles as $detalle) {
                // Handle Oracle object property casing (uppercase by default)
                $proCodigo = $detalle->PRO_CODIGO ?? $detalle->pro_codigo ?? $detalle->PRO_Codigo;

                $productoData = DB::table('productos')
                    ->where(DB::raw('UPPER(PRO_CODIGO)'), strtoupper($proCodigo))
                    ->first();

                if ($productoData) {
                    $nombre = $productoData->PRO_NOMBRE ?? $productoData->pro_nombre ?? $productoData->PRO_Nombre;
                    $desc = $productoData->PRO_DESCRIPCION ?? $productoData->pro_descripcion ?? $productoData->PRO_Descripcion ?? '';

                    $precio = $detalle->DFC_PRECIO ?? $detalle->dfc_precio ?? $detalle->DFC_Precio;
                    $cantidad = $detalle->DFC_CANTIDAD ?? $detalle->dfc_cantidad ?? $detalle->DFC_Cantidad;
                    $talla = $detalle->DFC_TALLA ?? $detalle->dfc_talla ?? $detalle->DFC_Talla ?? 'N/A';

                    $items[] = (new InvoiceItem())
                        ->title($nombre)
                        ->description("Talla: $talla")
                        ->pricePerUnit($precio)
                        ->quantity($cantidad);
                }
            }
        } else {
            foreach ($productos as $producto) {
                $talla = $producto->pivot->DFC_TALLA ?? $producto->pivot->DFC_Talla ?? 'N/A';
                $items[] = (new InvoiceItem())
                    ->title($producto->PRO_Nombre)
                    ->description("Talla: $talla")
                    ->pricePerUnit($producto->pivot->DFC_PRECIO ?? $producto->pivot->DFC_Precio)
                    ->quantity($producto->pivot->DFC_CANTIDAD ?? $producto->pivot->DFC_Cantidad);
            }
        }

        // Generate invoice
        $seller = new Party([
            'name' => config('app.name', 'UrbanHoops'),
            'address' => 'Dirección de la tienda',
            'code' => 'RUC: 1234567890001',
        ]);

        $invoice = Invoice::make('Factura')
            ->series('FAC')
            ->sequence(intval(substr($factura->FAC_Codigo, 3)))
            ->serialNumberFormat('{SERIES}{SEQUENCE}')
            ->delimiter('')
            ->seller($seller)
            ->buyer($buyer)
            ->date($factura->created_at)
            ->dateFormat('d/m/Y')
            ->payUntilDays(30)
            ->currencySymbol('$')
            ->currencyCode('USD')
            ->currencyFormat('{SYMBOL}{VALUE}')
            ->currencyThousandsSeparator(',')
            ->currencyDecimalPoint('.')
            ->filename($factura->FAC_Codigo)
            ->addItems($items)
            ->totalDiscount(0)
            ->taxRate(config('urbanhoops.iva', 15))
            ->shipping(0)
            ->notes('Gracias por su compra en UrbanHoops!')
            ->logo(public_path('images/logo_fondo_claro_admin.png'));

        return $invoice->stream();
    }
}
